In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
import os

# 종합유원시설업.csv 불러오기

In [3]:
file = pd.read_csv('data/종합유원시설업.csv', encoding='cp949')
file.head()

,번호,개방서비스명,개방서비스아이디,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태구분코드,영업상태명,상세영업상태코드,...,의무실유무,안내소유무,기획여행보험시작일자,기획여행보험종료일자,자본금,보험시작일자,보험종료일자,부대시설내역,시설규모,Unnamed: 63
0,1,종합유원시설업,03_07_12_P,3480000,CDFI5271002005000001,2005-07-22,NaN,2,휴업,2,...,N,Y,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN
1,2,종합유원시설업,03_07_12_P,5090000,CDFI5271002008000001,2008-07-18,NaN,2,휴업,2,...,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,종합유원시설업,03_07_12_P,3820000,CDFI5271002018000001,2018-06-20,NaN,2,휴업,2,...,Y,Y,NaN,NaN,0.0,NaN,NaN,NaN,18934.0,NaN
3,4,종합유원시설업,03_07_12_P,4281000,CDFI5271002008000001,2008-06-12,NaN,2,휴업,2,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN
4,5,종합유원시설업,03_07_12_P,5380000,CDFI5271001993000001,1993-04-30,NaN,2,휴업,2,...,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 필요한 컬럼만 갖고오기

In [4]:
file2 = file.loc[:,['영업상태명', '상세영업상태코드', '상세영업상태명', '소재지전화', '소재지전체주소', '도로명전체주소', '사업장명']]

In [5]:
file2

,영업상태명,상세영업상태코드,상세영업상태명,소재지전화,소재지전체주소,도로명전체주소,사업장명
0,휴업,2,휴업,053-608-5000,대구광역시 달성군 가창면 냉천리 27-9,대구광역시 달성군 가창면 가창로 891,주식회사 스파밸리
1,휴업,2,휴업,054-630-5500,경상북도 영주시 아지동 산 6번지,경상북도 영주시 회헌로 434 (아지동),판타시온 리조트
2,휴업,2,휴업,031-894-0357,경기도 의정부시 장암동 135 아일랜드캐슬 A동,"경기도 의정부시 장곡로 22, 아일랜드캐슬 A동 (장암동)",아일랜드캐슬
3,휴업,2,휴업,033-330-6000,강원특별자치도 평창군 봉평면 면온리 1095-1 (주)휘닉스평창,강원특별자치도 평창군 봉평면 태기로 174 (주)휘닉스평창,휘닉스 블루캐니언
4,휴업,2,휴업,379-7125,경상남도 양산시 하북면 순지리 470,경상남도 양산시 하북면 통도7길 68,(주)동일리조트 통도환타지아
...,...,...,...,...,...,...,...
73,취소/말소/만료/정지/중지,30,허가취소,041)939-9000,충청남도 보령시 신흑동 1945번지,충청남도 보령시 대해로 876 (신흑동),레그랜드펀비치 호텔앤워터파크
74,취소/말소/만료/정지/중지,30,허가취소,055-223-9561~5,경상남도 창원시 마산합포구 월영동 625,NaN,주식회사 가고파랜드
75,취소/말소/만료/정지/중지,30,허가취소,NaN,부산광역시 영도구 동삼동 1125번지,부산광역시 영도구 해양로 435-1 (동삼동),월드카니발 부산
76,취소/말소/만료/정지/중지,30,허가취소,02-454-4442,서울특별시 광진구 능동 18-0,서울특별시 광진구 능동로 216 (능동),어린이대공원놀이동산(주)
77,취소/말소/만료/정지/중지,30,허가취소,223-5118,충청북도 청주시 상당구 명암동 47-8번지,충청북도 청주시 상당구 명암로216번길 47 (명암동),(주)청주드림랜드

# 영업중인 사업장만 갖고오기

In [6]:
file3 = file2.loc[file2['상세영업상태코드']==13]

# nan값을 공백으로 바꾸기

In [7]:
#file3 = file3.fillna("")

In [8]:
file3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 46 entries, 27 to 72
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   영업상태명     46 non-null     object
 1   상세영업상태코드  46 non-null     int64
 2   상세영업상태명   46 non-null     object
 3   소재지전화     38 non-null     object
 4   소재지전체주소   46 non-null     object
 5   도로명전체주소   45 non-null     object
 6   사업장명      46 non-null     object
dtypes: int64(1), object(6)
memory usage: 2.9+ KB

In [9]:
file3

,영업상태명,상세영업상태코드,상세영업상태명,소재지전화,소재지전체주소,도로명전체주소,사업장명
27,영업/정상,13,영업중,053-620-0001,대구광역시 달서구 두류동 산 302-11,대구광역시 달서구 두류공원로 200 (두류동),이월드
28,영업/정상,13,영업중,051-954-8840,부산광역시 해운대구 중동 1829 엘시티,"부산광역시 해운대구 달맞이길 30, 포디움동 3,4층 (중동, 엘시티)",클럽디오아시스(CLUBD OASIS) 스파&워터파크
29,영업/정상,13,영업중,451-8500,경상북도 구미시 남통동 253,경상북도 구미시 금오산로 341 (남통동),금오랜드
30,영업/정상,13,영업중,041-560-9114,충청남도 천안시 동남구 수신면 장산리 669-1,충청남도 천안시 동남구 수신면 수신로 576,상록랜드
31,영업/정상,13,영업중,070-7433-3150,충청남도 천안시 동남구 성남면 용원리 672,충청남도 천안시 동남구 성남면 종합휴양지로 200,소노벨 천안
32,영업/정상,13,영업중,041-539-2000,충청남도 아산시 음봉면 신수리 288-0006,충청남도 아산시 음봉면 아산온천로157번길 67,(주)금호리조트아산스파비스
33,영업/정상,13,영업중,041-930-2100,충청남도 보령시 신흑동 1945,충청남도 보령시 대해로 876 (신흑동),호텔마스타 대천
34,영업/정상,13,영업중,320-8466,경기도 용인시 처인구 포곡읍 전대리 310,경기도 용인시 처인구 포곡읍 에버랜드로 199,에버랜드
35,영업/정상,13,영업중,320-8261,경기도 용인시 처인구 포곡읍 유운리 554-1,경기도 용인시 처인구 포곡읍 에버랜드로 199,캐리비안베이
36,영업/정상,13,영업중,031-286-2111,경기도 용인시 기흥구 보라동 107,경기도 용인시 기흥구 민속촌로 90 (보라동),한국민속촌 가족공원
37,영업/정상,13,영업중,1833-9810,제주특별자치도 제주시 애월읍 어음리 산 131,"제주특별자치도 제주시 애월읍 천덕로 880-24, 애월스마트테마파크",9.81 PARK JEJU
38,영업/정상,13,영업중,070-7113-6133,경상북도 경주시 천군동 191-5,경상북도 경주시 보문로 544 (천군동),경주월드주식회사 (경주지점)
39,영업/정상,13,영업중,054-778-9027,경상북도 경주시 천군동 산 31,"경상북도 경주시 보불로 391 (천군동, 디아너스C.C.골프클럽)",블루원 워터파크
40,영업/정상,13,영업중,031-8072-8802,경기도 하남시 신장동 616,"경기도 하남시 미사대로 750 (신장동, 스타필드하남)",아쿠아필드 하남
41,영업/정상,13,영업중,031-945-2250,경기도 파주시 조리읍 장곡리 420-6 하니랜드놀이동산,"경기도 파주시 조리읍 장곡로 218, 하니랜드놀이동산",하니랜드
42,영업/정상,13,영업중,031-880-3820,경기도 여주시 연양동 414,"경기도 여주시 강변유원지길 45 (연양동, 선밸리호텔)",주식회사 썬밸리
43,영업/정상,13,영업중,061-808-5846,전라남도 여수시 소라면 죽림리 116,전라남도 여수시 소라면 안심산길 155,유월드루지테마파크
44,영업/정상,13,영업중,NaN,강원특별자치도 횡성군 둔내면 두원리 204 웰리힐리파크,"강원특별자치도 횡성군 둔내면 고원로 451, 웰리힐리파크",웰리힐리파크 워터플래닛
45,영업/정상,13,영업중,NaN,강원특별자치도 횡성군 둔내면 두원리 204 웰리힐리파크,"강원특별자치도 횡성군 둔내면 고원로 451, 웰리힐리파크",웰리힐리파크 워터플래닛
46,영업/정상,13,영업중,252-7226,강원특별자치도 춘천시 사농동 61-2,강원특별자치도 춘천시 영서로 2965 (사농동),육림랜드
47,영업/정상,13,영업중,033-815-2300,강원특별자치도 춘천시 중도동 603,강원특별자치도 춘천시 하중도길 128 (중도동),레고랜드코리아
48,영업/정상,13,영업중,NaN,강원특별자치도 평창군 대관령면 용산리 130 용평피크아일랜드,"강원특별자치도 평창군 대관령면 올림픽로 715, 용평리조트",용평피크아일랜드
49,영업/정상,13,영업중,NaN,강원특별자치도 평창군 대관령면 용산리 425 알펜시아 리조트 오션700,"강원특별자치도 평창군 대관령면 솔봉로 325, 알펜시아 리조트",오션700
50,영업/정상,13,영업중,550-7788,강원특별자치도 삼척시 도계읍 심포리 231-3,강원특별자치도 삼척시 도계읍 심포남길 99,(주)하이원추추파크
51,영업/정상,13,영업중,0335906849,강원특별자치도 정선군 사북읍 사북리 산 155-58 하이원 워터월드,"강원특별자치도 정선군 사북읍 하이원길 175, 하이원 워터월드",하이원 워터월드
52,영업/정상,13,영업중,064-908-3325,제주특별자치도 서귀포시 안덕면 서광리 산 35-16,제주특별자치도 서귀포시 안덕면 신화역사로304번길 98,신화테마파크
53,영업/정상,13,영업중,064-908-6000,제주특별자치도 서귀포시 안덕면 서광리 산 35-16,제주특별자치도 서귀포시 안덕면 신화역사로304번길 98,신화워터파크
54,영업/정상,13,영업중,NaN,부산광역시 기장군 기장읍 시랑리 산 46,부산광역시 기장군 기장읍 동부산관광로 42,롯데월드 어드벤처 부산
55,영업/정상,13,영업중,033-439-8308,강원특별자치도 홍천군 서면 팔봉리 1289 대명비발디파크,"강원특별자치도 홍천군 서면 한치골길 264, 대명비발디파크",(주)소노인터내셔널 오션월드
56,영업/정상,13,영업중,033-635-7711,강원특별자치도 속초시 장사동 24-9,강원특별자치도 속초시 미시령로2983번길 88 (장사동),한화리조트(주) 설악워터피아
57,영업/정상,13,영업중,033-634-1000,강원특별자치도 속초시 대포동 908-1 롯데리조트속초,"강원특별자치도 속초시 대포항길 186, 롯데리조트속초 (대포동)",롯데리조트 속초 워터파크
58,영업/정상,13,영업중,061)689-861,전라남도 여수시 소호동 923 일원,"전라남도 여수시 소호로 295 (소호동, 디오션리조트)",에이치제이디오션리조트 주식회사
59,영업/정상,13,영업중,061-339-5000,전라남도 나주시 다도면 방산리 산 219-1,NaN,중흥골드스파&리조트
60,영업/정상,13,영업중,NaN,전라남도 화순군 도곡면 대곡리 1004-1,전라남도 화순군 도곡면 지석로 1202-7,테마파크 소풍
61,영업/정상,13,영업중,042-580-4710,대전광역시 중구 사정동 100,"대전광역시 중구 사정공원로 70 (사정동, 대전동물원)",대전오월드
62,영업/정상,13,영업중,NaN,경상남도 창원시 마산합포구 구산면 반동리 산 105,경상남도 창원시 마산합포구 구산면 로봇랜드로 250,로봇랜드
63,영업/정상,13,영업중,055-346-6000,경상남도 김해시 삼방동 산 123,경상남도 김해시 인제로 368 (삼방동),가야랜드
64,영업/정상,13,영업중,NaN,경상남도 거제시 일운면 소동리 115,경상남도 거제시 일운면 거제대로 2660,오션어드벤처
65,영업/정상,13,영업중,1588-0377,전라남도 여수시 소호동 923,전라남도 여수시 소호로 295 (소호동),에이치제이디오션리조트 주식회사
66,영업/정상,13,영업중,02-509-6000,경기도 과천시 막계동 33,경기도 과천시 광명로 181 (막계동),(주)서울랜드
67,영업/정상,13,영업중,02-450-9311,서울특별시 광진구 능동 18 어린이대공원,"서울특별시 광진구 능동로 216, 어린이대공원 (능동)",구미산업개발(주) 서울어린이대공원 놀이동산지점
68,영업/정상,13,영업중,032-310-8171,경기도 부천시 원미구 상동 572-1,경기도 부천시 원미구 조마루로 2 (상동),웅진플레이도시
69,영업/정상,13,영업중,062-607-8000,광주광역시 북구 생용동 138,광주광역시 북구 우치로 677 (생용동),광주패밀리랜드(주)
70,영업/정상,13,영업중,411-2223,서울특별시 송파구 잠실동 40-1,서울특별시 송파구 올림픽로 240 (잠실동),(주)롯데월드어드벤처
71,영업/정상,13,영업중,6925-2900,서울특별시 송파구 문정동 618 202동,"서울특별시 송파구 송파대로 111, 202동 지하1,2층 (문정동, 파크하비오)",워터킹덤
72,영업/정상,13,영업중,031-961-6107,경기도 고양시 일산서구 대화동 2606,경기도 고양시 일산서구 한류월드로 300 (대화동),(주)원마운트

In [10]:
file4 = file3.copy()

# 비어있는 도로명주소를 소재지전체주소에서 값 끌어오기

In [11]:
file3.fillna("")

,영업상태명,상세영업상태코드,상세영업상태명,소재지전화,소재지전체주소,도로명전체주소,사업장명
27,영업/정상,13,영업중,053-620-0001,대구광역시 달서구 두류동 산 302-11,대구광역시 달서구 두류공원로 200 (두류동),이월드
28,영업/정상,13,영업중,051-954-8840,부산광역시 해운대구 중동 1829 엘시티,"부산광역시 해운대구 달맞이길 30, 포디움동 3,4층 (중동, 엘시티)",클럽디오아시스(CLUBD OASIS) 스파&워터파크
29,영업/정상,13,영업중,451-8500,경상북도 구미시 남통동 253,경상북도 구미시 금오산로 341 (남통동),금오랜드
30,영업/정상,13,영업중,041-560-9114,충청남도 천안시 동남구 수신면 장산리 669-1,충청남도 천안시 동남구 수신면 수신로 576,상록랜드
31,영업/정상,13,영업중,070-7433-3150,충청남도 천안시 동남구 성남면 용원리 672,충청남도 천안시 동남구 성남면 종합휴양지로 200,소노벨 천안
32,영업/정상,13,영업중,041-539-2000,충청남도 아산시 음봉면 신수리 288-0006,충청남도 아산시 음봉면 아산온천로157번길 67,(주)금호리조트아산스파비스
33,영업/정상,13,영업중,041-930-2100,충청남도 보령시 신흑동 1945,충청남도 보령시 대해로 876 (신흑동),호텔마스타 대천
34,영업/정상,13,영업중,320-8466,경기도 용인시 처인구 포곡읍 전대리 310,경기도 용인시 처인구 포곡읍 에버랜드로 199,에버랜드
35,영업/정상,13,영업중,320-8261,경기도 용인시 처인구 포곡읍 유운리 554-1,경기도 용인시 처인구 포곡읍 에버랜드로 199,캐리비안베이
36,영업/정상,13,영업중,031-286-2111,경기도 용인시 기흥구 보라동 107,경기도 용인시 기흥구 민속촌로 90 (보라동),한국민속촌 가족공원
37,영업/정상,13,영업중,1833-9810,제주특별자치도 제주시 애월읍 어음리 산 131,"제주특별자치도 제주시 애월읍 천덕로 880-24, 애월스마트테마파크",9.81 PARK JEJU
38,영업/정상,13,영업중,070-7113-6133,경상북도 경주시 천군동 191-5,경상북도 경주시 보문로 544 (천군동),경주월드주식회사 (경주지점)
39,영업/정상,13,영업중,054-778-9027,경상북도 경주시 천군동 산 31,"경상북도 경주시 보불로 391 (천군동, 디아너스C.C.골프클럽)",블루원 워터파크
40,영업/정상,13,영업중,031-8072-8802,경기도 하남시 신장동 616,"경기도 하남시 미사대로 750 (신장동, 스타필드하남)",아쿠아필드 하남
41,영업/정상,13,영업중,031-945-2250,경기도 파주시 조리읍 장곡리 420-6 하니랜드놀이동산,"경기도 파주시 조리읍 장곡로 218, 하니랜드놀이동산",하니랜드
42,영업/정상,13,영업중,031-880-3820,경기도 여주시 연양동 414,"경기도 여주시 강변유원지길 45 (연양동, 선밸리호텔)",주식회사 썬밸리
43,영업/정상,13,영업중,061-808-5846,전라남도 여수시 소라면 죽림리 116,전라남도 여수시 소라면 안심산길 155,유월드루지테마파크
44,영업/정상,13,영업중,,강원특별자치도 횡성군 둔내면 두원리 204 웰리힐리파크,"강원특별자치도 횡성군 둔내면 고원로 451, 웰리힐리파크",웰리힐리파크 워터플래닛
45,영업/정상,13,영업중,,강원특별자치도 횡성군 둔내면 두원리 204 웰리힐리파크,"강원특별자치도 횡성군 둔내면 고원로 451, 웰리힐리파크",웰리힐리파크 워터플래닛
46,영업/정상,13,영업중,252-7226,강원특별자치도 춘천시 사농동 61-2,강원특별자치도 춘천시 영서로 2965 (사농동),육림랜드
47,영업/정상,13,영업중,033-815-2300,강원특별자치도 춘천시 중도동 603,강원특별자치도 춘천시 하중도길 128 (중도동),레고랜드코리아
48,영업/정상,13,영업중,,강원특별자치도 평창군 대관령면 용산리 130 용평피크아일랜드,"강원특별자치도 평창군 대관령면 올림픽로 715, 용평리조트",용평피크아일랜드
49,영업/정상,13,영업중,,강원특별자치도 평창군 대관령면 용산리 425 알펜시아 리조트 오션700,"강원특별자치도 평창군 대관령면 솔봉로 325, 알펜시아 리조트",오션700
50,영업/정상,13,영업중,550-7788,강원특별자치도 삼척시 도계읍 심포리 231-3,강원특별자치도 삼척시 도계읍 심포남길 99,(주)하이원추추파크
51,영업/정상,13,영업중,0335906849,강원특별자치도 정선군 사북읍 사북리 산 155-58 하이원 워터월드,"강원특별자치도 정선군 사북읍 하이원길 175, 하이원 워터월드",하이원 워터월드
52,영업/정상,13,영업중,064-908-3325,제주특별자치도 서귀포시 안덕면 서광리 산 35-16,제주특별자치도 서귀포시 안덕면 신화역사로304번길 98,신화테마파크
53,영업/정상,13,영업중,064-908-6000,제주특별자치도 서귀포시 안덕면 서광리 산 35-16,제주특별자치도 서귀포시 안덕면 신화역사로304번길 98,신화워터파크
54,영업/정상,13,영업중,,부산광역시 기장군 기장읍 시랑리 산 46,부산광역시 기장군 기장읍 동부산관광로 42,롯데월드 어드벤처 부산
55,영업/정상,13,영업중,033-439-8308,강원특별자치도 홍천군 서면 팔봉리 1289 대명비발디파크,"강원특별자치도 홍천군 서면 한치골길 264, 대명비발디파크",(주)소노인터내셔널 오션월드
56,영업/정상,13,영업중,033-635-7711,강원특별자치도 속초시 장사동 24-9,강원특별자치도 속초시 미시령로2983번길 88 (장사동),한화리조트(주) 설악워터피아
57,영업/정상,13,영업중,033-634-1000,강원특별자치도 속초시 대포동 908-1 롯데리조트속초,"강원특별자치도 속초시 대포항길 186, 롯데리조트속초 (대포동)",롯데리조트 속초 워터파크
58,영업/정상,13,영업중,061)689-861,전라남도 여수시 소호동 923 일원,"전라남도 여수시 소호로 295 (소호동, 디오션리조트)",에이치제이디오션리조트 주식회사
59,영업/정상,13,영업중,061-339-5000,전라남도 나주시 다도면 방산리 산 219-1,,중흥골드스파&리조트
60,영업/정상,13,영업중,,전라남도 화순군 도곡면 대곡리 1004-1,전라남도 화순군 도곡면 지석로 1202-7,테마파크 소풍
61,영업/정상,13,영업중,042-580-4710,대전광역시 중구 사정동 100,"대전광역시 중구 사정공원로 70 (사정동, 대전동물원)",대전오월드
62,영업/정상,13,영업중,,경상남도 창원시 마산합포구 구산면 반동리 산 105,경상남도 창원시 마산합포구 구산면 로봇랜드로 250,로봇랜드
63,영업/정상,13,영업중,055-346-6000,경상남도 김해시 삼방동 산 123,경상남도 김해시 인제로 368 (삼방동),가야랜드
64,영업/정상,13,영업중,,경상남도 거제시 일운면 소동리 115,경상남도 거제시 일운면 거제대로 2660,오션어드벤처
65,영업/정상,13,영업중,1588-0377,전라남도 여수시 소호동 923,전라남도 여수시 소호로 295 (소호동),에이치제이디오션리조트 주식회사
66,영업/정상,13,영업중,02-509-6000,경기도 과천시 막계동 33,경기도 과천시 광명로 181 (막계동),(주)서울랜드
67,영업/정상,13,영업중,02-450-9311,서울특별시 광진구 능동 18 어린이대공원,"서울특별시 광진구 능동로 216, 어린이대공원 (능동)",구미산업개발(주) 서울어린이대공원 놀이동산지점
68,영업/정상,13,영업중,032-310-8171,경기도 부천시 원미구 상동 572-1,경기도 부천시 원미구 조마루로 2 (상동),웅진플레이도시
69,영업/정상,13,영업중,062-607-8000,광주광역시 북구 생용동 138,광주광역시 북구 우치로 677 (생용동),광주패밀리랜드(주)
70,영업/정상,13,영업중,411-2223,서울특별시 송파구 잠실동 40-1,서울특별시 송파구 올림픽로 240 (잠실동),(주)롯데월드어드벤처
71,영업/정상,13,영업중,6925-2900,서울특별시 송파구 문정동 618 202동,"서울특별시 송파구 송파대로 111, 202동 지하1,2층 (문정동, 파크하비오)",워터킹덤
72,영업/정상,13,영업중,031-961-6107,경기도 고양시 일산서구 대화동 2606,경기도 고양시 일산서구 한류월드로 300 (대화동),(주)원마운트

In [12]:
file3["도로명전체주소"].fillna(file3['소재지전체주소'], inplace=True)

/var/folders/22/c_58xyrx5_3g8md1gqx1zz8r0000gn/T/ipykernel_20942/1611772268.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  file3["도로명전체주소"].fillna(file3['소재지전체주소'], inplace=True)

In [13]:
file3

,영업상태명,상세영업상태코드,상세영업상태명,소재지전화,소재지전체주소,도로명전체주소,사업장명
27,영업/정상,13,영업중,053-620-0001,대구광역시 달서구 두류동 산 302-11,대구광역시 달서구 두류공원로 200 (두류동),이월드
28,영업/정상,13,영업중,051-954-8840,부산광역시 해운대구 중동 1829 엘시티,"부산광역시 해운대구 달맞이길 30, 포디움동 3,4층 (중동, 엘시티)",클럽디오아시스(CLUBD OASIS) 스파&워터파크
29,영업/정상,13,영업중,451-8500,경상북도 구미시 남통동 253,경상북도 구미시 금오산로 341 (남통동),금오랜드
30,영업/정상,13,영업중,041-560-9114,충청남도 천안시 동남구 수신면 장산리 669-1,충청남도 천안시 동남구 수신면 수신로 576,상록랜드
31,영업/정상,13,영업중,070-7433-3150,충청남도 천안시 동남구 성남면 용원리 672,충청남도 천안시 동남구 성남면 종합휴양지로 200,소노벨 천안
32,영업/정상,13,영업중,041-539-2000,충청남도 아산시 음봉면 신수리 288-0006,충청남도 아산시 음봉면 아산온천로157번길 67,(주)금호리조트아산스파비스
33,영업/정상,13,영업중,041-930-2100,충청남도 보령시 신흑동 1945,충청남도 보령시 대해로 876 (신흑동),호텔마스타 대천
34,영업/정상,13,영업중,320-8466,경기도 용인시 처인구 포곡읍 전대리 310,경기도 용인시 처인구 포곡읍 에버랜드로 199,에버랜드
35,영업/정상,13,영업중,320-8261,경기도 용인시 처인구 포곡읍 유운리 554-1,경기도 용인시 처인구 포곡읍 에버랜드로 199,캐리비안베이
36,영업/정상,13,영업중,031-286-2111,경기도 용인시 기흥구 보라동 107,경기도 용인시 기흥구 민속촌로 90 (보라동),한국민속촌 가족공원
37,영업/정상,13,영업중,1833-9810,제주특별자치도 제주시 애월읍 어음리 산 131,"제주특별자치도 제주시 애월읍 천덕로 880-24, 애월스마트테마파크",9.81 PARK JEJU
38,영업/정상,13,영업중,070-7113-6133,경상북도 경주시 천군동 191-5,경상북도 경주시 보문로 544 (천군동),경주월드주식회사 (경주지점)
39,영업/정상,13,영업중,054-778-9027,경상북도 경주시 천군동 산 31,"경상북도 경주시 보불로 391 (천군동, 디아너스C.C.골프클럽)",블루원 워터파크
40,영업/정상,13,영업중,031-8072-8802,경기도 하남시 신장동 616,"경기도 하남시 미사대로 750 (신장동, 스타필드하남)",아쿠아필드 하남
41,영업/정상,13,영업중,031-945-2250,경기도 파주시 조리읍 장곡리 420-6 하니랜드놀이동산,"경기도 파주시 조리읍 장곡로 218, 하니랜드놀이동산",하니랜드
42,영업/정상,13,영업중,031-880-3820,경기도 여주시 연양동 414,"경기도 여주시 강변유원지길 45 (연양동, 선밸리호텔)",주식회사 썬밸리
43,영업/정상,13,영업중,061-808-5846,전라남도 여수시 소라면 죽림리 116,전라남도 여수시 소라면 안심산길 155,유월드루지테마파크
44,영업/정상,13,영업중,NaN,강원특별자치도 횡성군 둔내면 두원리 204 웰리힐리파크,"강원특별자치도 횡성군 둔내면 고원로 451, 웰리힐리파크",웰리힐리파크 워터플래닛
45,영업/정상,13,영업중,NaN,강원특별자치도 횡성군 둔내면 두원리 204 웰리힐리파크,"강원특별자치도 횡성군 둔내면 고원로 451, 웰리힐리파크",웰리힐리파크 워터플래닛
46,영업/정상,13,영업중,252-7226,강원특별자치도 춘천시 사농동 61-2,강원특별자치도 춘천시 영서로 2965 (사농동),육림랜드
47,영업/정상,13,영업중,033-815-2300,강원특별자치도 춘천시 중도동 603,강원특별자치도 춘천시 하중도길 128 (중도동),레고랜드코리아
48,영업/정상,13,영업중,NaN,강원특별자치도 평창군 대관령면 용산리 130 용평피크아일랜드,"강원특별자치도 평창군 대관령면 올림픽로 715, 용평리조트",용평피크아일랜드
49,영업/정상,13,영업중,NaN,강원특별자치도 평창군 대관령면 용산리 425 알펜시아 리조트 오션700,"강원특별자치도 평창군 대관령면 솔봉로 325, 알펜시아 리조트",오션700
50,영업/정상,13,영업중,550-7788,강원특별자치도 삼척시 도계읍 심포리 231-3,강원특별자치도 삼척시 도계읍 심포남길 99,(주)하이원추추파크
51,영업/정상,13,영업중,0335906849,강원특별자치도 정선군 사북읍 사북리 산 155-58 하이원 워터월드,"강원특별자치도 정선군 사북읍 하이원길 175, 하이원 워터월드",하이원 워터월드
52,영업/정상,13,영업중,064-908-3325,제주특별자치도 서귀포시 안덕면 서광리 산 35-16,제주특별자치도 서귀포시 안덕면 신화역사로304번길 98,신화테마파크
53,영업/정상,13,영업중,064-908-6000,제주특별자치도 서귀포시 안덕면 서광리 산 35-16,제주특별자치도 서귀포시 안덕면 신화역사로304번길 98,신화워터파크
54,영업/정상,13,영업중,NaN,부산광역시 기장군 기장읍 시랑리 산 46,부산광역시 기장군 기장읍 동부산관광로 42,롯데월드 어드벤처 부산
55,영업/정상,13,영업중,033-439-8308,강원특별자치도 홍천군 서면 팔봉리 1289 대명비발디파크,"강원특별자치도 홍천군 서면 한치골길 264, 대명비발디파크",(주)소노인터내셔널 오션월드
56,영업/정상,13,영업중,033-635-7711,강원특별자치도 속초시 장사동 24-9,강원특별자치도 속초시 미시령로2983번길 88 (장사동),한화리조트(주) 설악워터피아
57,영업/정상,13,영업중,033-634-1000,강원특별자치도 속초시 대포동 908-1 롯데리조트속초,"강원특별자치도 속초시 대포항길 186, 롯데리조트속초 (대포동)",롯데리조트 속초 워터파크
58,영업/정상,13,영업중,061)689-861,전라남도 여수시 소호동 923 일원,"전라남도 여수시 소호로 295 (소호동, 디오션리조트)",에이치제이디오션리조트 주식회사
59,영업/정상,13,영업중,061-339-5000,전라남도 나주시 다도면 방산리 산 219-1,전라남도 나주시 다도면 방산리 산 219-1,중흥골드스파&리조트
60,영업/정상,13,영업중,NaN,전라남도 화순군 도곡면 대곡리 1004-1,전라남도 화순군 도곡면 지석로 1202-7,테마파크 소풍
61,영업/정상,13,영업중,042-580-4710,대전광역시 중구 사정동 100,"대전광역시 중구 사정공원로 70 (사정동, 대전동물원)",대전오월드
62,영업/정상,13,영업중,NaN,경상남도 창원시 마산합포구 구산면 반동리 산 105,경상남도 창원시 마산합포구 구산면 로봇랜드로 250,로봇랜드
63,영업/정상,13,영업중,055-346-6000,경상남도 김해시 삼방동 산 123,경상남도 김해시 인제로 368 (삼방동),가야랜드
64,영업/정상,13,영업중,NaN,경상남도 거제시 일운면 소동리 115,경상남도 거제시 일운면 거제대로 2660,오션어드벤처
65,영업/정상,13,영업중,1588-0377,전라남도 여수시 소호동 923,전라남도 여수시 소호로 295 (소호동),에이치제이디오션리조트 주식회사
66,영업/정상,13,영업중,02-509-6000,경기도 과천시 막계동 33,경기도 과천시 광명로 181 (막계동),(주)서울랜드
67,영업/정상,13,영업중,02-450-9311,서울특별시 광진구 능동 18 어린이대공원,"서울특별시 광진구 능동로 216, 어린이대공원 (능동)",구미산업개발(주) 서울어린이대공원 놀이동산지점
68,영업/정상,13,영업중,032-310-8171,경기도 부천시 원미구 상동 572-1,경기도 부천시 원미구 조마루로 2 (상동),웅진플레이도시
69,영업/정상,13,영업중,062-607-8000,광주광역시 북구 생용동 138,광주광역시 북구 우치로 677 (생용동),광주패밀리랜드(주)
70,영업/정상,13,영업중,411-2223,서울특별시 송파구 잠실동 40-1,서울특별시 송파구 올림픽로 240 (잠실동),(주)롯데월드어드벤처
71,영업/정상,13,영업중,6925-2900,서울특별시 송파구 문정동 618 202동,"서울특별시 송파구 송파대로 111, 202동 지하1,2층 (문정동, 파크하비오)",워터킹덤
72,영업/정상,13,영업중,031-961-6107,경기도 고양시 일산서구 대화동 2606,경기도 고양시 일산서구 한류월드로 300 (대화동),(주)원마운트

# 새로운 "분류" 컬럼 생성하기

In [14]:
file3 = file3.drop(['영업상태명', '상세영업상태코드', '상세영업상태명', '소재지전화', '소재지전체주소'], axis=1)

In [18]:
file3['분류'] = "테마파크"
file3

,도로명전체주소,사업장명,분류
27,대구광역시 달서구 두류공원로 200 (두류동),이월드,테마파크
28,"부산광역시 해운대구 달맞이길 30, 포디움동 3,4층 (중동, 엘시티)",클럽디오아시스(CLUBD OASIS) 스파&워터파크,테마파크
29,경상북도 구미시 금오산로 341 (남통동),금오랜드,테마파크
30,충청남도 천안시 동남구 수신면 수신로 576,상록랜드,테마파크
31,충청남도 천안시 동남구 성남면 종합휴양지로 200,소노벨 천안,테마파크
32,충청남도 아산시 음봉면 아산온천로157번길 67,(주)금호리조트아산스파비스,테마파크
33,충청남도 보령시 대해로 876 (신흑동),호텔마스타 대천,테마파크
34,경기도 용인시 처인구 포곡읍 에버랜드로 199,에버랜드,테마파크
35,경기도 용인시 처인구 포곡읍 에버랜드로 199,캐리비안베이,테마파크
36,경기도 용인시 기흥구 민속촌로 90 (보라동),한국민속촌 가족공원,테마파크
37,"제주특별자치도 제주시 애월읍 천덕로 880-24, 애월스마트테마파크",9.81 PARK JEJU,테마파크
38,경상북도 경주시 보문로 544 (천군동),경주월드주식회사 (경주지점),테마파크
39,"경상북도 경주시 보불로 391 (천군동, 디아너스C.C.골프클럽)",블루원 워터파크,테마파크
40,"경기도 하남시 미사대로 750 (신장동, 스타필드하남)",아쿠아필드 하남,테마파크
41,"경기도 파주시 조리읍 장곡로 218, 하니랜드놀이동산",하니랜드,테마파크
42,"경기도 여주시 강변유원지길 45 (연양동, 선밸리호텔)",주식회사 썬밸리,테마파크
43,전라남도 여수시 소라면 안심산길 155,유월드루지테마파크,테마파크
44,"강원특별자치도 횡성군 둔내면 고원로 451, 웰리힐리파크",웰리힐리파크 워터플래닛,테마파크
45,"강원특별자치도 횡성군 둔내면 고원로 451, 웰리힐리파크",웰리힐리파크 워터플래닛,테마파크
46,강원특별자치도 춘천시 영서로 2965 (사농동),육림랜드,테마파크
47,강원특별자치도 춘천시 하중도길 128 (중도동),레고랜드코리아,테마파크
48,"강원특별자치도 평창군 대관령면 올림픽로 715, 용평리조트",용평피크아일랜드,테마파크
49,"강원특별자치도 평창군 대관령면 솔봉로 325, 알펜시아 리조트",오션700,테마파크
50,강원특별자치도 삼척시 도계읍 심포남길 99,(주)하이원추추파크,테마파크
51,"강원특별자치도 정선군 사북읍 하이원길 175, 하이원 워터월드",하이원 워터월드,테마파크
52,제주특별자치도 서귀포시 안덕면 신화역사로304번길 98,신화테마파크,테마파크
53,제주특별자치도 서귀포시 안덕면 신화역사로304번길 98,신화워터파크,테마파크
54,부산광역시 기장군 기장읍 동부산관광로 42,롯데월드 어드벤처 부산,테마파크
55,"강원특별자치도 홍천군 서면 한치골길 264, 대명비발디파크",(주)소노인터내셔널 오션월드,테마파크
56,강원특별자치도 속초시 미시령로2983번길 88 (장사동),한화리조트(주) 설악워터피아,테마파크
57,"강원특별자치도 속초시 대포항길 186, 롯데리조트속초 (대포동)",롯데리조트 속초 워터파크,테마파크
58,"전라남도 여수시 소호로 295 (소호동, 디오션리조트)",에이치제이디오션리조트 주식회사,테마파크
59,전라남도 나주시 다도면 방산리 산 219-1,중흥골드스파&리조트,테마파크
60,전라남도 화순군 도곡면 지석로 1202-7,테마파크 소풍,테마파크
61,"대전광역시 중구 사정공원로 70 (사정동, 대전동물원)",대전오월드,테마파크
62,경상남도 창원시 마산합포구 구산면 로봇랜드로 250,로봇랜드,테마파크
63,경상남도 김해시 인제로 368 (삼방동),가야랜드,테마파크
64,경상남도 거제시 일운면 거제대로 2660,오션어드벤처,테마파크
65,전라남도 여수시 소호로 295 (소호동),에이치제이디오션리조트 주식회사,테마파크
66,경기도 과천시 광명로 181 (막계동),(주)서울랜드,테마파크
67,"서울특별시 광진구 능동로 216, 어린이대공원 (능동)",구미산업개발(주) 서울어린이대공원 놀이동산지점,테마파크
68,경기도 부천시 원미구 조마루로 2 (상동),웅진플레이도시,테마파크
69,광주광역시 북구 우치로 677 (생용동),광주패밀리랜드(주),테마파크
70,서울특별시 송파구 올림픽로 240 (잠실동),(주)롯데월드어드벤처,테마파크
71,"서울특별시 송파구 송파대로 111, 202동 지하1,2층 (문정동, 파크하비오)",워터킹덤,테마파크
72,경기도 고양시 일산서구 한류월드로 300 (대화동),(주)원마운트,테마파크

In [19]:
file3.columns = ['city', 'place_name', 'category']

In [73]:
file3

,place_name,place_desc,category,city,rating,num_reviews
0,이월드,,테마파크,대구광역시 달서구 두류공원로 200 (두류동),0,0
1,클럽디오아시스(CLUBD OASIS) 스파&워터파크,,테마파크,"부산광역시 해운대구 달맞이길 30, 포디움동 3,4층 (중동, 엘시티)",0,0
2,금오랜드,,테마파크,경상북도 구미시 금오산로 341 (남통동),0,0
3,상록랜드,,테마파크,충청남도 천안시 동남구 수신면 수신로 576,0,0
4,소노벨 천안,,테마파크,충청남도 천안시 동남구 성남면 종합휴양지로 200,0,0
5,(주)금호리조트아산스파비스,,테마파크,충청남도 아산시 음봉면 아산온천로157번길 67,0,0
6,호텔마스타 대천,,테마파크,충청남도 보령시 대해로 876 (신흑동),0,0
7,에버랜드,,테마파크,경기도 용인시 처인구 포곡읍 에버랜드로 199,0,0
8,캐리비안베이,,테마파크,경기도 용인시 처인구 포곡읍 에버랜드로 199,0,0
9,한국민속촌 가족공원,,테마파크,경기도 용인시 기흥구 민속촌로 90 (보라동),0,0
10,9.81 PARK JEJU,,테마파크,"제주특별자치도 제주시 애월읍 천덕로 880-24, 애월스마트테마파크",0,0
11,경주월드주식회사 (경주지점),,테마파크,경상북도 경주시 보문로 544 (천군동),0,0
12,블루원 워터파크,,테마파크,"경상북도 경주시 보불로 391 (천군동, 디아너스C.C.골프클럽)",0,0
13,아쿠아필드 하남,,테마파크,"경기도 하남시 미사대로 750 (신장동, 스타필드하남)",0,0
14,하니랜드,,테마파크,"경기도 파주시 조리읍 장곡로 218, 하니랜드놀이동산",0,0
15,주식회사 썬밸리,,테마파크,"경기도 여주시 강변유원지길 45 (연양동, 선밸리호텔)",0,0
16,유월드루지테마파크,,테마파크,전라남도 여수시 소라면 안심산길 155,0,0
17,웰리힐리파크 워터플래닛,,테마파크,"강원특별자치도 횡성군 둔내면 고원로 451, 웰리힐리파크",0,0
18,웰리힐리파크 워터플래닛,,테마파크,"강원특별자치도 횡성군 둔내면 고원로 451, 웰리힐리파크",0,0
19,육림랜드,,테마파크,강원특별자치도 춘천시 영서로 2965 (사농동),0,0
20,레고랜드코리아,,테마파크,강원특별자치도 춘천시 하중도길 128 (중도동),0,0
21,용평피크아일랜드,,테마파크,"강원특별자치도 평창군 대관령면 올림픽로 715, 용평리조트",0,0
22,오션700,,테마파크,"강원특별자치도 평창군 대관령면 솔봉로 325, 알펜시아 리조트",0,0
23,(주)하이원추추파크,,테마파크,강원특별자치도 삼척시 도계읍 심포남길 99,0,0
24,하이원 워터월드,,테마파크,"강원특별자치도 정선군 사북읍 하이원길 175, 하이원 워터월드",0,0
25,신화테마파크,,테마파크,제주특별자치도 서귀포시 안덕면 신화역사로304번길 98,0,0
26,신화워터파크,,테마파크,제주특별자치도 서귀포시 안덕면 신화역사로304번길 98,0,0
27,롯데월드 어드벤처 부산,,테마파크,부산광역시 기장군 기장읍 동부산관광로 42,0,0
28,(주)소노인터내셔널 오션월드,,테마파크,"강원특별자치도 홍천군 서면 한치골길 264, 대명비발디파크",0,0
29,한화리조트(주) 설악워터피아,,테마파크,강원특별자치도 속초시 미시령로2983번길 88 (장사동),0,0
30,롯데리조트 속초 워터파크,,테마파크,"강원특별자치도 속초시 대포항길 186, 롯데리조트속초 (대포동)",0,0
31,에이치제이디오션리조트 주식회사,,테마파크,"전라남도 여수시 소호로 295 (소호동, 디오션리조트)",0,0
32,중흥골드스파&리조트,,테마파크,전라남도 나주시 다도면 방산리 산 219-1,0,0
33,테마파크 소풍,,테마파크,전라남도 화순군 도곡면 지석로 1202-7,0,0
34,대전오월드,,테마파크,"대전광역시 중구 사정공원로 70 (사정동, 대전동물원)",0,0
35,로봇랜드,,테마파크,경상남도 창원시 마산합포구 구산면 로봇랜드로 250,0,0
36,가야랜드,,테마파크,경상남도 김해시 인제로 368 (삼방동),0,0
37,오션어드벤처,,테마파크,경상남도 거제시 일운면 거제대로 2660,0,0
38,에이치제이디오션리조트 주식회사,,테마파크,전라남도 여수시 소호로 295 (소호동),0,0
39,(주)서울랜드,,테마파크,경기도 과천시 광명로 181 (막계동),0,0
40,구미산업개발(주) 서울어린이대공원 놀이동산지점,,테마파크,"서울특별시 광진구 능동로 216, 어린이대공원 (능동)",0,0
41,웅진플레이도시,,테마파크,경기도 부천시 원미구 조마루로 2 (상동),0,0
42,광주패밀리랜드(주),,테마파크,광주광역시 북구 우치로 677 (생용동),0,0
43,(주)롯데월드어드벤처,,테마파크,서울특별시 송파구 올림픽로 240 (잠실동),0,0
44,워터킹덤,,테마파크,"서울특별시 송파구 송파대로 111, 202동 지하1,2층 (문정동, 파크하비오)",0,0
45,(주)원마운트,,테마파크,경기도 고양시 일산서구 한류월드로 300 (대화동),0,0

In [74]:
file3.to_csv("data/pj1_amusementpark_01.csv", encoding='cp949')

In [22]:
file3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 46 entries, 27 to 72
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   city        46 non-null     object
 1   place_name  46 non-null     object
 2   category    46 non-null     object
dtypes: object(3)
memory usage: 1.4+ KB

In [25]:
file3 = file3.reset_index(drop=True)

In [26]:
file3

,city,place_name,category
0,대구광역시 달서구 두류공원로 200 (두류동),이월드,테마파크
1,"부산광역시 해운대구 달맞이길 30, 포디움동 3,4층 (중동, 엘시티)",클럽디오아시스(CLUBD OASIS) 스파&워터파크,테마파크
2,경상북도 구미시 금오산로 341 (남통동),금오랜드,테마파크
3,충청남도 천안시 동남구 수신면 수신로 576,상록랜드,테마파크
4,충청남도 천안시 동남구 성남면 종합휴양지로 200,소노벨 천안,테마파크
5,충청남도 아산시 음봉면 아산온천로157번길 67,(주)금호리조트아산스파비스,테마파크
6,충청남도 보령시 대해로 876 (신흑동),호텔마스타 대천,테마파크
7,경기도 용인시 처인구 포곡읍 에버랜드로 199,에버랜드,테마파크
8,경기도 용인시 처인구 포곡읍 에버랜드로 199,캐리비안베이,테마파크
9,경기도 용인시 기흥구 민속촌로 90 (보라동),한국민속촌 가족공원,테마파크
10,"제주특별자치도 제주시 애월읍 천덕로 880-24, 애월스마트테마파크",9.81 PARK JEJU,테마파크
11,경상북도 경주시 보문로 544 (천군동),경주월드주식회사 (경주지점),테마파크
12,"경상북도 경주시 보불로 391 (천군동, 디아너스C.C.골프클럽)",블루원 워터파크,테마파크
13,"경기도 하남시 미사대로 750 (신장동, 스타필드하남)",아쿠아필드 하남,테마파크
14,"경기도 파주시 조리읍 장곡로 218, 하니랜드놀이동산",하니랜드,테마파크
15,"경기도 여주시 강변유원지길 45 (연양동, 선밸리호텔)",주식회사 썬밸리,테마파크
16,전라남도 여수시 소라면 안심산길 155,유월드루지테마파크,테마파크
17,"강원특별자치도 횡성군 둔내면 고원로 451, 웰리힐리파크",웰리힐리파크 워터플래닛,테마파크
18,"강원특별자치도 횡성군 둔내면 고원로 451, 웰리힐리파크",웰리힐리파크 워터플래닛,테마파크
19,강원특별자치도 춘천시 영서로 2965 (사농동),육림랜드,테마파크
20,강원특별자치도 춘천시 하중도길 128 (중도동),레고랜드코리아,테마파크
21,"강원특별자치도 평창군 대관령면 올림픽로 715, 용평리조트",용평피크아일랜드,테마파크
22,"강원특별자치도 평창군 대관령면 솔봉로 325, 알펜시아 리조트",오션700,테마파크
23,강원특별자치도 삼척시 도계읍 심포남길 99,(주)하이원추추파크,테마파크
24,"강원특별자치도 정선군 사북읍 하이원길 175, 하이원 워터월드",하이원 워터월드,테마파크
25,제주특별자치도 서귀포시 안덕면 신화역사로304번길 98,신화테마파크,테마파크
26,제주특별자치도 서귀포시 안덕면 신화역사로304번길 98,신화워터파크,테마파크
27,부산광역시 기장군 기장읍 동부산관광로 42,롯데월드 어드벤처 부산,테마파크
28,"강원특별자치도 홍천군 서면 한치골길 264, 대명비발디파크",(주)소노인터내셔널 오션월드,테마파크
29,강원특별자치도 속초시 미시령로2983번길 88 (장사동),한화리조트(주) 설악워터피아,테마파크
30,"강원특별자치도 속초시 대포항길 186, 롯데리조트속초 (대포동)",롯데리조트 속초 워터파크,테마파크
31,"전라남도 여수시 소호로 295 (소호동, 디오션리조트)",에이치제이디오션리조트 주식회사,테마파크
32,전라남도 나주시 다도면 방산리 산 219-1,중흥골드스파&리조트,테마파크
33,전라남도 화순군 도곡면 지석로 1202-7,테마파크 소풍,테마파크
34,"대전광역시 중구 사정공원로 70 (사정동, 대전동물원)",대전오월드,테마파크
35,경상남도 창원시 마산합포구 구산면 로봇랜드로 250,로봇랜드,테마파크
36,경상남도 김해시 인제로 368 (삼방동),가야랜드,테마파크
37,경상남도 거제시 일운면 거제대로 2660,오션어드벤처,테마파크
38,전라남도 여수시 소호로 295 (소호동),에이치제이디오션리조트 주식회사,테마파크
39,경기도 과천시 광명로 181 (막계동),(주)서울랜드,테마파크
40,"서울특별시 광진구 능동로 216, 어린이대공원 (능동)",구미산업개발(주) 서울어린이대공원 놀이동산지점,테마파크
41,경기도 부천시 원미구 조마루로 2 (상동),웅진플레이도시,테마파크
42,광주광역시 북구 우치로 677 (생용동),광주패밀리랜드(주),테마파크
43,서울특별시 송파구 올림픽로 240 (잠실동),(주)롯데월드어드벤처,테마파크
44,"서울특별시 송파구 송파대로 111, 202동 지하1,2층 (문정동, 파크하비오)",워터킹덤,테마파크
45,경기도 고양시 일산서구 한류월드로 300 (대화동),(주)원마운트,테마파크

# sql에 넣기

In [3]:
import pymysql

In [66]:
conn = pymysql.connect(host='192.168.0.103', user='user1', password='u1234', db='project01', charset='utf8')
cur=conn.cursor()

In [37]:
file3 = file3[['place_name', 'category', 'city']]

In [69]:
file3['place_desc'] = ""
file3['rating'] = 0
file3['num_reviews'] = 0

In [47]:
file3 = file3[['place_name', 'place_desc', 'category', 'city', 'rating', 'num_reviews']]

In [70]:
file3

,place_name,place_desc,category,city,rating,num_reviews
0,이월드,,테마파크,대구광역시 달서구 두류공원로 200 (두류동),0,0
1,클럽디오아시스(CLUBD OASIS) 스파&워터파크,,테마파크,"부산광역시 해운대구 달맞이길 30, 포디움동 3,4층 (중동, 엘시티)",0,0
2,금오랜드,,테마파크,경상북도 구미시 금오산로 341 (남통동),0,0
3,상록랜드,,테마파크,충청남도 천안시 동남구 수신면 수신로 576,0,0
4,소노벨 천안,,테마파크,충청남도 천안시 동남구 성남면 종합휴양지로 200,0,0
5,(주)금호리조트아산스파비스,,테마파크,충청남도 아산시 음봉면 아산온천로157번길 67,0,0
6,호텔마스타 대천,,테마파크,충청남도 보령시 대해로 876 (신흑동),0,0
7,에버랜드,,테마파크,경기도 용인시 처인구 포곡읍 에버랜드로 199,0,0
8,캐리비안베이,,테마파크,경기도 용인시 처인구 포곡읍 에버랜드로 199,0,0
9,한국민속촌 가족공원,,테마파크,경기도 용인시 기흥구 민속촌로 90 (보라동),0,0
10,9.81 PARK JEJU,,테마파크,"제주특별자치도 제주시 애월읍 천덕로 880-24, 애월스마트테마파크",0,0
11,경주월드주식회사 (경주지점),,테마파크,경상북도 경주시 보문로 544 (천군동),0,0
12,블루원 워터파크,,테마파크,"경상북도 경주시 보불로 391 (천군동, 디아너스C.C.골프클럽)",0,0
13,아쿠아필드 하남,,테마파크,"경기도 하남시 미사대로 750 (신장동, 스타필드하남)",0,0
14,하니랜드,,테마파크,"경기도 파주시 조리읍 장곡로 218, 하니랜드놀이동산",0,0
15,주식회사 썬밸리,,테마파크,"경기도 여주시 강변유원지길 45 (연양동, 선밸리호텔)",0,0
16,유월드루지테마파크,,테마파크,전라남도 여수시 소라면 안심산길 155,0,0
17,웰리힐리파크 워터플래닛,,테마파크,"강원특별자치도 횡성군 둔내면 고원로 451, 웰리힐리파크",0,0
18,웰리힐리파크 워터플래닛,,테마파크,"강원특별자치도 횡성군 둔내면 고원로 451, 웰리힐리파크",0,0
19,육림랜드,,테마파크,강원특별자치도 춘천시 영서로 2965 (사농동),0,0
20,레고랜드코리아,,테마파크,강원특별자치도 춘천시 하중도길 128 (중도동),0,0
21,용평피크아일랜드,,테마파크,"강원특별자치도 평창군 대관령면 올림픽로 715, 용평리조트",0,0
22,오션700,,테마파크,"강원특별자치도 평창군 대관령면 솔봉로 325, 알펜시아 리조트",0,0
23,(주)하이원추추파크,,테마파크,강원특별자치도 삼척시 도계읍 심포남길 99,0,0
24,하이원 워터월드,,테마파크,"강원특별자치도 정선군 사북읍 하이원길 175, 하이원 워터월드",0,0
25,신화테마파크,,테마파크,제주특별자치도 서귀포시 안덕면 신화역사로304번길 98,0,0
26,신화워터파크,,테마파크,제주특별자치도 서귀포시 안덕면 신화역사로304번길 98,0,0
27,롯데월드 어드벤처 부산,,테마파크,부산광역시 기장군 기장읍 동부산관광로 42,0,0
28,(주)소노인터내셔널 오션월드,,테마파크,"강원특별자치도 홍천군 서면 한치골길 264, 대명비발디파크",0,0
29,한화리조트(주) 설악워터피아,,테마파크,강원특별자치도 속초시 미시령로2983번길 88 (장사동),0,0
30,롯데리조트 속초 워터파크,,테마파크,"강원특별자치도 속초시 대포항길 186, 롯데리조트속초 (대포동)",0,0
31,에이치제이디오션리조트 주식회사,,테마파크,"전라남도 여수시 소호로 295 (소호동, 디오션리조트)",0,0
32,중흥골드스파&리조트,,테마파크,전라남도 나주시 다도면 방산리 산 219-1,0,0
33,테마파크 소풍,,테마파크,전라남도 화순군 도곡면 지석로 1202-7,0,0
34,대전오월드,,테마파크,"대전광역시 중구 사정공원로 70 (사정동, 대전동물원)",0,0
35,로봇랜드,,테마파크,경상남도 창원시 마산합포구 구산면 로봇랜드로 250,0,0
36,가야랜드,,테마파크,경상남도 김해시 인제로 368 (삼방동),0,0
37,오션어드벤처,,테마파크,경상남도 거제시 일운면 거제대로 2660,0,0
38,에이치제이디오션리조트 주식회사,,테마파크,전라남도 여수시 소호로 295 (소호동),0,0
39,(주)서울랜드,,테마파크,경기도 과천시 광명로 181 (막계동),0,0
40,구미산업개발(주) 서울어린이대공원 놀이동산지점,,테마파크,"서울특별시 광진구 능동로 216, 어린이대공원 (능동)",0,0
41,웅진플레이도시,,테마파크,경기도 부천시 원미구 조마루로 2 (상동),0,0
42,광주패밀리랜드(주),,테마파크,광주광역시 북구 우치로 677 (생용동),0,0
43,(주)롯데월드어드벤처,,테마파크,서울특별시 송파구 올림픽로 240 (잠실동),0,0
44,워터킹덤,,테마파크,"서울특별시 송파구 송파대로 111, 202동 지하1,2층 (문정동, 파크하비오)",0,0
45,(주)원마운트,,테마파크,경기도 고양시 일산서구 한류월드로 300 (대화동),0,0

In [67]:
for index, row in file3.iterrows():
    cur.execute("""
        INSERT INTO places(
            place_name,
            place_desc,
            category,
            city,
            rating,
            num_reviews) VALUES (%s, %s, %s, %s, %s, %s)""",
        (row['place_name'],
         row['place_desc'],
         row['category'],
         row['city'],
         row['rating'],
         row['num_reviews']))

ProgrammingError: nan can not be used with MySQL

In [68]:
#conn.commit()
conn.close()

In [72]:
file3.drop_duplicates(['place_name'])

,place_name,place_desc,category,city,rating,num_reviews
0,이월드,,테마파크,대구광역시 달서구 두류공원로 200 (두류동),0,0
1,클럽디오아시스(CLUBD OASIS) 스파&워터파크,,테마파크,"부산광역시 해운대구 달맞이길 30, 포디움동 3,4층 (중동, 엘시티)",0,0
2,금오랜드,,테마파크,경상북도 구미시 금오산로 341 (남통동),0,0
3,상록랜드,,테마파크,충청남도 천안시 동남구 수신면 수신로 576,0,0
4,소노벨 천안,,테마파크,충청남도 천안시 동남구 성남면 종합휴양지로 200,0,0
5,(주)금호리조트아산스파비스,,테마파크,충청남도 아산시 음봉면 아산온천로157번길 67,0,0
6,호텔마스타 대천,,테마파크,충청남도 보령시 대해로 876 (신흑동),0,0
7,에버랜드,,테마파크,경기도 용인시 처인구 포곡읍 에버랜드로 199,0,0
8,캐리비안베이,,테마파크,경기도 용인시 처인구 포곡읍 에버랜드로 199,0,0
9,한국민속촌 가족공원,,테마파크,경기도 용인시 기흥구 민속촌로 90 (보라동),0,0
10,9.81 PARK JEJU,,테마파크,"제주특별자치도 제주시 애월읍 천덕로 880-24, 애월스마트테마파크",0,0
11,경주월드주식회사 (경주지점),,테마파크,경상북도 경주시 보문로 544 (천군동),0,0
12,블루원 워터파크,,테마파크,"경상북도 경주시 보불로 391 (천군동, 디아너스C.C.골프클럽)",0,0
13,아쿠아필드 하남,,테마파크,"경기도 하남시 미사대로 750 (신장동, 스타필드하남)",0,0
14,하니랜드,,테마파크,"경기도 파주시 조리읍 장곡로 218, 하니랜드놀이동산",0,0
15,주식회사 썬밸리,,테마파크,"경기도 여주시 강변유원지길 45 (연양동, 선밸리호텔)",0,0
16,유월드루지테마파크,,테마파크,전라남도 여수시 소라면 안심산길 155,0,0
17,웰리힐리파크 워터플래닛,,테마파크,"강원특별자치도 횡성군 둔내면 고원로 451, 웰리힐리파크",0,0
19,육림랜드,,테마파크,강원특별자치도 춘천시 영서로 2965 (사농동),0,0
20,레고랜드코리아,,테마파크,강원특별자치도 춘천시 하중도길 128 (중도동),0,0
21,용평피크아일랜드,,테마파크,"강원특별자치도 평창군 대관령면 올림픽로 715, 용평리조트",0,0
22,오션700,,테마파크,"강원특별자치도 평창군 대관령면 솔봉로 325, 알펜시아 리조트",0,0
23,(주)하이원추추파크,,테마파크,강원특별자치도 삼척시 도계읍 심포남길 99,0,0
24,하이원 워터월드,,테마파크,"강원특별자치도 정선군 사북읍 하이원길 175, 하이원 워터월드",0,0
25,신화테마파크,,테마파크,제주특별자치도 서귀포시 안덕면 신화역사로304번길 98,0,0
26,신화워터파크,,테마파크,제주특별자치도 서귀포시 안덕면 신화역사로304번길 98,0,0
27,롯데월드 어드벤처 부산,,테마파크,부산광역시 기장군 기장읍 동부산관광로 42,0,0
28,(주)소노인터내셔널 오션월드,,테마파크,"강원특별자치도 홍천군 서면 한치골길 264, 대명비발디파크",0,0
29,한화리조트(주) 설악워터피아,,테마파크,강원특별자치도 속초시 미시령로2983번길 88 (장사동),0,0
30,롯데리조트 속초 워터파크,,테마파크,"강원특별자치도 속초시 대포항길 186, 롯데리조트속초 (대포동)",0,0
31,에이치제이디오션리조트 주식회사,,테마파크,"전라남도 여수시 소호로 295 (소호동, 디오션리조트)",0,0
32,중흥골드스파&리조트,,테마파크,전라남도 나주시 다도면 방산리 산 219-1,0,0
33,테마파크 소풍,,테마파크,전라남도 화순군 도곡면 지석로 1202-7,0,0
34,대전오월드,,테마파크,"대전광역시 중구 사정공원로 70 (사정동, 대전동물원)",0,0
35,로봇랜드,,테마파크,경상남도 창원시 마산합포구 구산면 로봇랜드로 250,0,0
36,가야랜드,,테마파크,경상남도 김해시 인제로 368 (삼방동),0,0
37,오션어드벤처,,테마파크,경상남도 거제시 일운면 거제대로 2660,0,0
39,(주)서울랜드,,테마파크,경기도 과천시 광명로 181 (막계동),0,0
40,구미산업개발(주) 서울어린이대공원 놀이동산지점,,테마파크,"서울특별시 광진구 능동로 216, 어린이대공원 (능동)",0,0
41,웅진플레이도시,,테마파크,경기도 부천시 원미구 조마루로 2 (상동),0,0
42,광주패밀리랜드(주),,테마파크,광주광역시 북구 우치로 677 (생용동),0,0
43,(주)롯데월드어드벤처,,테마파크,서울특별시 송파구 올림픽로 240 (잠실동),0,0
44,워터킹덤,,테마파크,"서울특별시 송파구 송파대로 111, 202동 지하1,2층 (문정동, 파크하비오)",0,0
45,(주)원마운트,,테마파크,경기도 고양시 일산서구 한류월드로 300 (대화동),0,0