In [1]:
import requests
from bs4 import BeautifulSoup
import re
from konlpy.tag import Okt
from collections import Counter
import pandas as pd
from wordcloud import WordCloud
import matplotlib.pyplot as plt
import time

In [12]:
# 파일 로드

def load_file(fileName):

    return pd.read_csv(f'data/{fileName}', encoding='cp949', index_col=0)

In [13]:
load_file('pj1_amusementpark_01.csv')

,place_name,place_desc,category,city,rating,num_reviews
0,이월드,NaN,테마파크,대구광역시 달서구 두류공원로 200 (두류동),0,0
1,클럽디오아시스(CLUBD OASIS) 스파&워터파크,NaN,테마파크,"부산광역시 해운대구 달맞이길 30, 포디움동 3,4층 (중동, 엘시티)",0,0
2,금오랜드,NaN,테마파크,경상북도 구미시 금오산로 341 (남통동),0,0
3,상록랜드,NaN,테마파크,충청남도 천안시 동남구 수신면 수신로 576,0,0
4,소노벨 천안,NaN,테마파크,충청남도 천안시 동남구 성남면 종합휴양지로 200,0,0
5,(주)금호리조트아산스파비스,NaN,테마파크,충청남도 아산시 음봉면 아산온천로157번길 67,0,0
6,호텔마스타 대천,NaN,테마파크,충청남도 보령시 대해로 876 (신흑동),0,0
7,에버랜드,NaN,테마파크,경기도 용인시 처인구 포곡읍 에버랜드로 199,0,0
8,캐리비안베이,NaN,테마파크,경기도 용인시 처인구 포곡읍 에버랜드로 199,0,0
9,한국민속촌 가족공원,NaN,테마파크,경기도 용인시 기흥구 민속촌로 90 (보라동),0,0
10,9.81 PARK JEJU,NaN,테마파크,"제주특별자치도 제주시 애월읍 천덕로 880-24, 애월스마트테마파크",0,0
11,경주월드주식회사 (경주지점),NaN,테마파크,경상북도 경주시 보문로 544 (천군동),0,0
12,블루원 워터파크,NaN,테마파크,"경상북도 경주시 보불로 391 (천군동, 디아너스C.C.골프클럽)",0,0
13,아쿠아필드 하남,NaN,테마파크,"경기도 하남시 미사대로 750 (신장동, 스타필드하남)",0,0
14,하니랜드,NaN,테마파크,"경기도 파주시 조리읍 장곡로 218, 하니랜드놀이동산",0,0
15,주식회사 썬밸리,NaN,테마파크,"경기도 여주시 강변유원지길 45 (연양동, 선밸리호텔)",0,0
16,유월드루지테마파크,NaN,테마파크,전라남도 여수시 소라면 안심산길 155,0,0
17,웰리힐리파크 워터플래닛,NaN,테마파크,"강원특별자치도 횡성군 둔내면 고원로 451, 웰리힐리파크",0,0
18,웰리힐리파크 워터플래닛,NaN,테마파크,"강원특별자치도 횡성군 둔내면 고원로 451, 웰리힐리파크",0,0
19,육림랜드,NaN,테마파크,강원특별자치도 춘천시 영서로 2965 (사농동),0,0
20,레고랜드코리아,NaN,테마파크,강원특별자치도 춘천시 하중도길 128 (중도동),0,0
21,용평피크아일랜드,NaN,테마파크,"강원특별자치도 평창군 대관령면 올림픽로 715, 용평리조트",0,0
22,오션700,NaN,테마파크,"강원특별자치도 평창군 대관령면 솔봉로 325, 알펜시아 리조트",0,0
23,(주)하이원추추파크,NaN,테마파크,강원특별자치도 삼척시 도계읍 심포남길 99,0,0
24,하이원 워터월드,NaN,테마파크,"강원특별자치도 정선군 사북읍 하이원길 175, 하이원 워터월드",0,0
25,신화테마파크,NaN,테마파크,제주특별자치도 서귀포시 안덕면 신화역사로304번길 98,0,0
26,신화워터파크,NaN,테마파크,제주특별자치도 서귀포시 안덕면 신화역사로304번길 98,0,0
27,롯데월드 어드벤처 부산,NaN,테마파크,부산광역시 기장군 기장읍 동부산관광로 42,0,0
28,(주)소노인터내셔널 오션월드,NaN,테마파크,"강원특별자치도 홍천군 서면 한치골길 264, 대명비발디파크",0,0
29,한화리조트(주) 설악워터피아,NaN,테마파크,강원특별자치도 속초시 미시령로2983번길 88 (장사동),0,0
30,롯데리조트 속초 워터파크,NaN,테마파크,"강원특별자치도 속초시 대포항길 186, 롯데리조트속초 (대포동)",0,0
31,에이치제이디오션리조트 주식회사,NaN,테마파크,"전라남도 여수시 소호로 295 (소호동, 디오션리조트)",0,0
32,중흥골드스파&리조트,NaN,테마파크,전라남도 나주시 다도면 방산리 산 219-1,0,0
33,테마파크 소풍,NaN,테마파크,전라남도 화순군 도곡면 지석로 1202-7,0,0
34,대전오월드,NaN,테마파크,"대전광역시 중구 사정공원로 70 (사정동, 대전동물원)",0,0
35,로봇랜드,NaN,테마파크,경상남도 창원시 마산합포구 구산면 로봇랜드로 250,0,0
36,가야랜드,NaN,테마파크,경상남도 김해시 인제로 368 (삼방동),0,0
37,오션어드벤처,NaN,테마파크,경상남도 거제시 일운면 거제대로 2660,0,0
38,에이치제이디오션리조트 주식회사,NaN,테마파크,전라남도 여수시 소호로 295 (소호동),0,0
39,(주)서울랜드,NaN,테마파크,경기도 과천시 광명로 181 (막계동),0,0
40,구미산업개발(주) 서울어린이대공원 놀이동산지점,NaN,테마파크,"서울특별시 광진구 능동로 216, 어린이대공원 (능동)",0,0
41,웅진플레이도시,NaN,테마파크,경기도 부천시 원미구 조마루로 2 (상동),0,0
42,광주패밀리랜드(주),NaN,테마파크,광주광역시 북구 우치로 677 (생용동),0,0
43,(주)롯데월드어드벤처,NaN,테마파크,서울특별시 송파구 올림픽로 240 (잠실동),0,0
44,워터킹덤,NaN,테마파크,"서울특별시 송파구 송파대로 111, 202동 지하1,2층 (문정동, 파크하비오)",0,0
45,(주)원마운트,NaN,테마파크,경기도 고양시 일산서구 한류월드로 300 (대화동),0,0

In [15]:
# place_name 갖고오기

def get_key(amuse):

    keyword_list=[]

    for keyword in amuse['place_name']:
        #print(keyword)
        keyword = keyword.replace(" ", "+")
        keyword_list.append(keyword)

    return keyword_list

In [16]:
keyword_list= get_key(load_file('pj1_amusementpark_01.csv'))

print(keyword_list)

['이월드', '클럽디오아시스(CLUBD+OASIS)+스파&워터파크', '금오랜드', '상록랜드', '소노벨+천안', '(주)금호리조트아산스파비스', '호텔마스타+대천', '에버랜드', '캐리비안베이', '한국민속촌+가족공원', '9.81+PARK+JEJU', '경주월드주식회사+(경주지점)', '블루원+워터파크', '아쿠아필드+하남', '하니랜드', '주식회사+썬밸리', '유월드루지테마파크', '웰리힐리파크+워터플래닛', '웰리힐리파크+워터플래닛', '육림랜드', '레고랜드코리아', '용평피크아일랜드', '오션700', '(주)하이원추추파크', '하이원+워터월드', '신화테마파크', '신화워터파크', '롯데월드+어드벤처+부산', '(주)소노인터내셔널+오션월드', '한화리조트(주)+설악워터피아', '롯데리조트+속초+워터파크', '에이치제이디오션리조트+주식회사', '중흥골드스파&리조트', '테마파크+소풍', '대전오월드', '로봇랜드', '가야랜드', '오션어드벤처', '에이치제이디오션리조트+주식회사', '(주)서울랜드', '구미산업개발(주)+서울어린이대공원+놀이동산지점', '웅진플레이도시', '광주패밀리랜드(주)', '(주)롯데월드어드벤처', '워터킹덤', '(주)원마운트']

In [17]:
def url_raw(keyword_list):

    titleList = []
    amuse_df = pd.DataFrame()

    for keyword in keyword_list[:5]:

        # 키워드 별로 담기 위해 리스트 초기화
        titleList = []

        # 페이지 수 지정하여 for문 실행
        for i in range(1, 3, 1):
            url = f"https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q={keyword}&p={i}"
            print(url)
            response = requests.get(url) # url 갖고오기
            html = response.text # text만 갖고오기
            soup = BeautifulSoup(html, 'html.parser') # 파싱하기

            titles = soup.select("ul.c-list-basic") # c-list-basic 클래스에서 ul에 묶여있는 요소들을 모두 갖고온다
            #subtitles = soup.select("a.elss.sub_tit")
            for title in titles : # titles에서 title   # 갖고온 요소로 for문 실행
                titleText = title.text # title.text만 추출
                titleList.append(titleText) # titleList에 추가

    return titleList

In [20]:
url_rawData = url_raw(keyword_list)

https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q=이월드&p=1
https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q=이월드&p=2
https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q=클럽디오아시스(CLUBD+OASIS)+스파&워터파크&p=1
https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q=클럽디오아시스(CLUBD+OASIS)+스파&워터파크&p=2
https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q=금오랜드&p=1
https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q=금오랜드&p=2
https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q=상록랜드&p=1
https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q=상록랜드&p=2
https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q=소노벨+천안&p=1
https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q=소노벨+천안&p=2

In [22]:
def text_cleaning(text) :
    hangul = re.compile('[^ ㄱ-ㅣ가-힣]+')
    result = hangul.sub('', text)
    return result

In [28]:
def filtering_keyword(titleList):
            
# 한글만 추출하기
    titleList = list(map(lambda x:text_cleaning(x), titleList))
    #print(titleList)
    
    title_corpus = " ".join(titleList) # 추출한 각 요소를 띄어쓰기로 join
    nouns_tagger = Okt() # 형태소 초기화
    nouns = nouns_tagger.nouns(title_corpus) # 명사 추출
    
    count = Counter(nouns) # 명사 갯수 세기

    #print(count)
    
    remove_char_counter = Counter({x:count[x] for x in count if len(x) > 1})    # 데이터 길이가 1보다 큰 것만 필터링
    #print(remove_char_counter)
    
    # 불용어 처리 경로 지정
    korean_stopwords_path = "data/stopwords-ko.txt"
    
    # stopwords 파일 열기
    with open(korean_stopwords_path, encoding='utf8') as f:
        stopwords = f.readlines()
    stopwords = [x.strip() for x in stopwords]
    
     # 위에서 필터링한 리스트를 하나씩 for 문 돌려서 stopwords에 해당되지 않는 것만 갯수 세기
    remove_char_counter = Counter({x:remove_char_counter[x] for x in remove_char_counter if x not in stopwords})
    #print(remove_char_counter)

    return remove_char_counter

In [29]:
remove_char_counter = filtering_keyword(url_rawData)

In [39]:

def trans_dict(remove_char_counter):

    # 빈도수 오름차순으로 50개 가져오기
    ranked_tags = remove_char_counter.most_common(50) # 빈도순 n개 단어
    # 딕셔너리로 변환
    ranked_tags = dict(ranked_tags)
    # 단어와 빈도를 dataframe으로 갖고오기
    df = pd.DataFrame(ranked_tags.items(), columns=['단어', '빈도'])
    
    return df

In [40]:
df = trans_dict(remove_char_counter)

print(df)

       단어  빈도
0      천안  35
1      노벨  24
2      창업  14
3      캠프  11
4      충남  10
5      프레   9
6      웨이   9
7      강원   8
8      리솜   8
9      컬처   8
10     파크   7
11    박람회   7
12  독립기념관   7
13   셔틀버스   7
14     시즌   6
15     세션   6
16     성장   6
17     식음   6
18    서비스   6
19   오션월드   6
20     개최   6
21    리조트   6
22     학생   6
23    브랜드   5
24    스토어   5
25     보증   5
26     일간   5
27     임시   5
28    주차장   5
29     운행   5
30    대전대   5
31     학년   5
32     호텔   4
33     비치   4
34     서울   4
35     홍천   4
36     스플   4
37     라스   4
38     예산   4
39     웰리   4
40     힐리   4
41     횡성   4
42   포레스트   4
43     충북   4
44     팩트   4
45     농협   4
46     코스   4
47     주차   4
48     편의   4
49     위해   4

In [41]:
print(trans_dict(filtering_keyword(url_raw(get_key(load_file('pj1_amusementpark_01.csv'))))))

https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q=이월드&p=1
https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q=이월드&p=2
https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q=클럽디오아시스(CLUBD+OASIS)+스파&워터파크&p=1
https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q=클럽디오아시스(CLUBD+OASIS)+스파&워터파크&p=2
https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q=금오랜드&p=1
https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q=금오랜드&p=2
https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q=상록랜드&p=1
https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q=상록랜드&p=2
https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q=소노벨+천안&p=1
https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q=소노벨+천안&p=2
       단어  빈도
0      천안  35
1      노벨  24
2      창업  14
3      캠프  11
4      충남  10
5      프레   9
6      웨이   9
7      강원   8
8      리솜   8
9      컬처   8
10     파크   7
11    박람회   7
12  독립기념관   7
13   셔틀버스   7
14     시즌   6
15     세션   6
16     성장   6
17     식음   6
18    서비스   6
19   오션월드   6
20     개최   6
21    리조트   6
22     학생   6
23    브랜드   5
24    스토어   5
25     보증   5
26     일간   5
27     임시   5
28    주차장   5
29     운행   5
30    대전대   5
31     학년   5
32     호텔   4
33     비치   4
34     서울   4
35     홍천   4
36     스플   4
37     라스   4
38     예산   4
39     웰리   4
40     힐리   4
41     횡성   4
42   포레스트   4
43     충북   4
44     팩트   4
45     농협   4
46     코스   4
47     주차   4
48     편의   4
49     위해   4